Update requirements.txt
keystone in the requirements.txt requests the wrong KS
Remove from requirements. Also from issue

https://github.com/senzee1984/micr0_shell/issues/3

Traceback (most recent call last):
File "micr0shell.py", line 398, in
ks = Ks(KS_ARCH_X86, KS_MODE_64)
NameError: name 'Ks' is not defined